### ISSUE TITLE
Golangで書き換える&退会機能を実装する

### ISSUE THREAD

**Issue by hayato24s** [twin-te/user-service#6]
[go/master](https://github.com/twin-te/user-service/tree/go/master)にコードがあります。

### Done
- Golangで既存のuser-serviceを書き換える
- 退会機能の実装
- デプロイ用の[Dockerfile](https://github.com/twin-te/user-service/blob/go/master/Dockerfile)の作成
- [migration](https://github.com/twin-te/user-service/tree/go/master/db/migrations)ツールの導入

### Todo
- [ ] [このような](https://github.com/twin-te/user-service/tree/master/.github/workflows)workflowの設定
- [ ] [submodule](https://github.com/twin-te/callback-handler/tree/master/services)の更新
- [ ] [proto file生成スクリプト](https://github.com/twin-te/callback-handler/blob/3f9715d01bce396856b0c04b5373433157c42821/proto-gen.sh#L7-L23)の更新

**Comment by hayato24s** [comment]
`yarn install`を実行するとき、`grpc-tools`のダウンロードでエラーが発生する。

下記の記事によると、m1 macを使用している場合インストールに失敗するらしい。
- https://qiita.com/uasi/items/93ccbde60b4397a83da9
- https://stackoverflow.com/questions/71420286/unable-to-install-grpc-tools-via-npm-or-yarn-on-mac-m1-chip

```
 > [twinte-cource-service-dev-image-for-apigateway build-env 6/9] RUN yarn:
#0 0.587 yarn install v1.22.19
#0 0.655 [1/4] Resolving packages...
#0 0.954 [2/4] Fetching packages...
#0 29.86 [3/4] Linking dependencies...
#0 29.87 warning "twinte-parser > axios-cookiejar-support@1.0.1" has unmet peer dependency "@types/tough-cookie@>=2.3.3".
#0 38.52 [4/4] Building fresh packages...
#0 39.41 error /usr/src/app/node_modules/grpc-tools: Command failed.
#0 39.41 Exit code: 1
#0 39.41 Command: node-pre-gyp install
#0 39.41 Arguments: 
#0 39.41 Directory: /usr/src/app/node_modules/grpc-tools
#0 39.41 Output:
#0 39.41 node-pre-gyp info it worked if it ends with ok
#0 39.41 node-pre-gyp info using node-pre-gyp@0.15.0
#0 39.41 node-pre-gyp info using node@14.21.3 | linux | arm64
#0 39.41 node-pre-gyp WARN Using request for node-pre-gyp https download 
#0 39.41 node-pre-gyp info check checked for "/usr/src/app/node_modules/grpc-tools/bin/grpc_tools.node" (not found)
#0 39.41 node-pre-gyp http GET https://node-precompiled-binaries.grpc.io/grpc-tools/v1.10.0/linux-arm64.tar.gz
#0 39.41 node-pre-gyp http 404 https://node-precompiled-binaries.grpc.io/grpc-tools/v1.10.0/linux-arm64.tar.gz
#0 39.41 node-pre-gyp ERR! install error 
#0 39.41 node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc-tools/v1.10.0/linux-arm64.tar.gz
#0 39.41 node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/src/app/node_modules/node-pre-gyp/lib/install.js:142:27)
#0 39.41 node-pre-gyp ERR! stack     at Request.emit (events.js:412:35)
#0 39.41 node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/src/app/node_modules/request/request.js:1059:10)
#0 39.41 node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:400:28)
#0 39.41 node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
#0 39.41 node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
#0 39.41 node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:515:22)
#0 39.41 node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:400:28)
#0 39.41 node-pre-gyp ERR! stack     at addChunk (internal/streams/readable.js:293:12)
#0 39.41 node-pre-gyp ERR! stack     at readableAddChunk (internal/streams/readable.js:267:9)
#0 39.41 node-pre-gyp ERR! System Linux 5.15.49-linuxkit
#0 39.41 node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/grpc-tools/node_modules/.bin/node-pre-gyp" "install"
#0 39.41 node-pre-gyp ERR! cwd /usr/src/app/node_modules/grpc-tools
#0 39.41 node-pre-gyp ERR! node -v v14.21.3
#0 39.41 node-pre-gyp ERR! node-pre-gyp -v v0.15.0
#0 39.41 node-pre-gyp ERR! not ok 
#0 39.41 404 status code downloading tarball https://node-precompiled-binaries.grpc.io/grpc-tools/v1.10.0/linux-arm64.tar.gz
#0 39.41 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn]: exit code: 1

```

下記のコマンドを実行したらインストールできた。
```
yarn add grpc-tools --ignore-scripts
pushd node_modules/grpc-tools
node_modules/.bin/node-pre-gyp install --target_arch=x64
popd
```

しかし、[こちら](https://github.com/twin-te/api-gateway/blob/master/.devcontainer/docker-compose.yml)のファイルではDocker imageが使用されているため、`grpc-tools`をインストールするタイミングでエラーが発生してしまう。

各サービスを上記のコマンドを実行しながら一つずつ立ち上げればエラーは回避できるかもしれない。

**Comment by hayato24s** [comment]
## session-serviceが起動しなかった

https://qiita.com/dtan4/items/45ae1a8ac6f853a0dc1a
